# Generated by Django 4.1.5 on 2023-01-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeDetails',
            fields=[
                ('uuid', models.IntegerField(primary_key=True, serialize=False)),
                ('address_full', models.CharField(max_length=200)),
                ('property_type', models.CharField(max_length=200)),
                ('sewer', models.CharField(max_length=10)),
                ('year_built', models.IntegerField(default=0)),
            ],
        ),
    ]
