# Generated by Django 4.1.5 on 2023-01-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homedetails',
            name='uuid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
